### A Pluto.jl notebook ###
# v0.11.12

using Markdown
using InteractiveUtils

# ╔═╡ 9b86a5d6-ef88-11ea-1913-cfd038289a63
# include -
include("$(_PATH_TO_ROOT)/Include.jl")

# ╔═╡ 5c65ec36-ef8f-11ea-2d24-3dc9d8b81763
md" ##### Reversible and irreversible isothermic expansion of a non-ideal gas

Throughout CHEME 3130 we will need to evaluate integrals in a variety of contexts. However, unlike previous courses where integrals could typically be evaluated analytically e.g., using simplified material models such the ideal-gas law, we often encounter cases where the analytical solution is difficult to evaluate. For example, the calculation of work can be challenging for modern equations of state. 

Work generated by the expansion of a real gas (non-ideal) from an inital volume $V_{1}$ to a final volume $V_{2}$ along an isotherm at temperature $T$ can be computed by evaluating the integral:

$$W = -\int_{V_{1}}^{V_{2}}P_{x}dV$$

where $P_{x}\simeq{P_{system}}$ in the reversible case. For an irreversibe transformation



"

# ╔═╡ ae8754ea-ef88-11ea-3b39-e9f799fad7bc
md" ##### Numerical evaluation of of definate integrals

The numerical evaluation of integrals is a huge topic area, with many different approaches ranging from [Newton–Cotes quadrature rules](https://en.wikipedia.org/wiki/Newton–Cotes_formulas) to [Monte-Carlo integration](https://en.wikipedia.org/wiki/Monte_Carlo_integration).  
The [Riemann sum](https://en.wikipedia.org/wiki/Riemann_sum) is one of the simplest ways to an estimate the value of a definate integral.
In this approach, the integral is broken down into the finite sum of steps over the interval $[a,b]$:

$$\int_{a}^{b}f(x)dx \simeq \sum_{i=1}^{N}f\left(x_{i}^{*}\right)\Delta{x}_{i}$$

where the step size (for a fixed step size) is given by:

$$\Delta{x} = \frac{b - a}{N}$$

The function is evaluated at points along the interval where the choice of $x_{i}^{*}$ is specific to a 
particular [Riemann sum](https://en.wikipedia.org/wiki/Riemann_sum) approach.
"

# ╔═╡ Cell order:
# ╟─5c65ec36-ef8f-11ea-2d24-3dc9d8b81763
# ╟─ae8754ea-ef88-11ea-3b39-e9f799fad7bc
# ╠═9b86a5d6-ef88-11ea-1913-cfd038289a63
